version: "3.9"
services:
  api_web:
    image: cnbian/laobian-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Source=Local
      - DbLocation=../../test/test_data/db_repo
      - BlogPostLocation=../../test/test_data/blog_post_repo
      - FileServerBaseUrl=/
    ports:
      - "5010:5010"
  admin_web:
    image: cnbian/laobian-admin:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiLocalEndPoint=http://127.0.0.1:5010
      - BlogRemoteEndPoint=http://127.0.0.1:5012
      - AdminName=admin
      - AdminPassword=admin
    ports:
      - "5011:5011"
    depends_on:
      - api_web
  blog_web:
    image: cnbian/laobian-blog:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiLocalEndPoint=http://127.0.0.1:5010
      - PotsPerPage=8
      - AdminEmail=test@test.com
      - AdminChineName=中文名
      - AdminEnglishName=English Name
      - BlogPostLocation=../../test/test_data/blog_post_repo
      - FileServerBaseUrl=/
    ports:
      - "5012:5012"
    depends_on:
      - api_web