version: "3.9"
services:
  api:
    image: cnbian/laobian-api:latest
    volumes:
      - ${ENV_API_DB_VOLUME}:/db
      - ${ENV_API_BLOG_POST_VOLUME}:/blog_post
    environment:
      - ASPNETCORE_URLS=http://127.0.0.1:5010
      - ASPNETCORE_ENVIRONMENT
      - ENV_API_Source
      - ENV_API_DbLocation=/db
      - ENV_API_BlogPostLocation/blog_post
  admin:
    image: cnbian/laobian-admin:latest
    environment:
      - ASPNETCORE_URLS=http://127.0.0.1:5011
      - ASPNETCORE_ENVIRONMENT
      - ENV_ADMIN_ApiLocalEndPoint=http://api:5010
      - ENV_ADMIN_BlogRemoteEndPoint
      - ENV_ADMIN_AdminName
      - ENV_ADMIN_AdminPassword
    ports:
      - "5011:5011"
    depends_on:
      - api
  blog:
    image: cnbian/laobian-blog:latest
    volumes:
      - ${ENV_API_BLOG_POST_VOLUME}:/blog_post
    environment:
      - ASPNETCORE_URLS=http://127.0.0.1:5012
      - ASPNETCORE_ENVIRONMENT
      - ENV_BLOG_ApiLocalEndPoint=http://api:5010
      - ENV_BLOG_PotsPerPage
      - ENV_BLOG_AdminEmail
      - ENV_BLOG_AdminChineName
      - ENV_BLOG_AdminEnglishName
      - ENV_BLOG_BlogPostLocation=/blog_post
    ports:
      - "5012:5012"
    depends_on:
      - api

volumes: 
